Universal-OSBB/Universal-OSBB/Models/Repository/NewsHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Universal_OSBB.Models.Context;
using Universal_OSBB.Models.Entities;
using System.Data.Entity;

namespace Universal_OSBB.Models.Repository
{
    public class NewsHelper
    {
        static OOABContext db = new OOABContext();

        public static List<Message> GetAllNews(int id_osbb)
        {
            return db.Messages.Include(o => o.Owner).Where(o => o.Owner.OOABID == id_osbb).OrderByDescending(d => d.DatePublication).ToList<Message>();
        }

        public static List<Message> GetLastFiveNews(int id_osbb)
        {
            return db.Messages.Include(o => o.Owner).Where(o => o.Owner.OOABID == id_osbb).OrderByDescending(d => d.DatePublication).Take(5).ToList<Message>();
        }

        public static Message GetNoveltyByID(int identificator)
        {
            return db.Messages.Include(o => o.Owner).Where(id => id.MessageID == identificator).First();
        }

        public static List<File> GetFilesByMessageID(int identificator)
        {
            return db.Files.Where(id => id.MessageID == identificator).ToList<File>();
        }

        public static List<Comment> GetCommentsByMessageID(int identificator)
        {
            return db.Comments.Include(o => o.Owner).Where(id => id.MessageID == identificator)
                   .OrderByDescending(d => d.DateAdding).ToList<Comment>();
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/NoveltyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Context;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class NoveltyController : Controller
    {
        OOABContext db = new OOABContext();

        public ActionResult News()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(NewsHelper.GetAllNews(id_osbb));
        }

        public ActionResult CreateNovelty()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitCreateNovelty(Message message, HttpPostedFileBase upload)
        {
            message.DatePublication = DateTime.Now;
            message.OwnerID = int.Parse(Session["user_id"].ToString());
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                Message LastMessage = db.Messages.Where(id => id.MessageID == message.MessageID).First<Message>();
                if (upload != null)
                {
                    File file = new File();
                    file.Name = System.IO.Path.GetFileName(upload.FileName);
                    file.MessageID = LastMessage.MessageID;
                    db.Files.Add(file);
                    db.SaveChanges();
                    file = db.Files.Where(id => id.FileID == file.FileID).First();

                    //виділення розширення файлу
                    int i = file.Name.Length;
                    while (i >= 0 && String.Compare(file.Name[i - 1].ToString(), ".") != 0)
                        i--;

                    file.Name = file.Name.Insert(i - 1, file.FileID.ToString());
                    db.SaveChanges();
                    upload.SaveAs(Server.MapPath("~/FilesForNews/" + file.Name));

                }
                return View("News", NewsHelper.GetAllNews(OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()))));
            }
            else
            {
                return View("CreateNovelty");
            }
            
        }

        public ActionResult DetailsNovelty(int id)
        {
            return View(NewsHelper.GetNoveltyByID(id));
        }

        public ActionResult FilesMessage(int id)
        {
            return PartialView(NewsHelper.GetFilesByMessageID(id));
        }

        public FileResult DownloadFile(string filename)
        {
            // Путь до файлу
            string filepath = Server.MapPath("~/FilesForNews/" + filename);
            string filetype = "";

            if (filename.Contains(".pdf"))
                filetype = "application/pdf";
            else
                if (filename.Contains(".docx") || filename.Contains(".doc"))
                    filetype = "application/doc";

            if (String.Compare(filetype, "") == 0)
                return File(filepath, filename);
            return File(filepath, filetype, filename);
        }

        public ActionResult CommentsNovelty(int id)
        {
            return PartialView(NewsHelper.GetCommentsByMessageID(id));
        }

        public ActionResult AddComment(int id_owner, int id_message, string text_comment)
        {
            Comment comment = new Comment();
            comment.Text = text_comment;
            comment.DateAdding = DateTime.Now;
            comment.OwnerID = id_owner;
            comment.MessageID = id_message;
            db.Comments.Add(comment);
            db.SaveChanges();

            return View("DetailsNovelty", NewsHelper.GetNoveltyByID(id_message));
        }
    }
}

Universal-OSBB/Universal-OSBB/Views/Novelty/CommentsNovelty.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Comment>

@foreach (var item in Model)
{
    <fieldset style="width:80%; margin:0 auto;">
        <table>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
            </tr>
        </table>
        <p class="rightdate">
            Опубліковано: @Html.DisplayFor(modelItem => item.DateAdding), @Html.ActionLink(item.Owner.Surname + " "
                  + item.Owner.Name + " "
                  + item.Owner.MiddleName, "DetailsOwner", "Owner", new { id = item.OwnerID }, null)
        </p>
    </fieldset>
}

Universal-OSBB/Universal-OSBB/Views/Novelty/CreateNovelty.cshtml
@model Universal_OSBB.Models.Entities.Message

@using (Html.BeginForm("SubmitCreateNovelty", "Novelty", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <fieldset>
        <legend>Розміщення повідомлення</legend>

        <p>@Html.ValidationSummary()</p>

        <span class="editor-label">
            @Html.LabelFor(model => model.Topic):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Topic)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Text):
        </span>
        <br>
        <span class="editor-field">
            @Html.TextAreaFor(model => model.Text, rows: 5, columns: 80, htmlAttributes: null)
        </span>
        <br>

        Завантажити файл:
        <br>
        <input type="file" name="upload"/>
        <br>
        <p>
            <input class="mybutton" type="submit" value="Опублікувати" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("До списку новин", "News", "Novelty")
</div>

Universal-OSBB/Universal-OSBB/Views/Novelty/DetailsNovelty.cshtml
@model Universal_OSBB.Models.Entities.Message

<fieldset>
    <legend>@Model.Topic</legend>

    <span class="display-label">
        @Html.DisplayFor(model => model.Text)
    </span>
    <br>  
    
    @Html.Action("FilesMessage", "Novelty", new { id = Model.MessageID })

    <div class="display-label" style="text-align:right">
        @Html.DisplayNameFor(model => model.DatePublication): @Html.DisplayFor(modelItem => modelItem.DatePublication),
        @Html.ActionLink(Model.Owner.Surname + " " + Model.Owner.Name + " " + Model.Owner.MiddleName, "DetailsOwner", "Owner", new { id = Model.OwnerID }, null)
    </div>
</fieldset>

<fieldset style="width:80%; margin:0 auto;">
    <legend style="font-weight: normal;">Додати коментар</legend>
    @using (Html.BeginForm("AddComment", "Novelty", new { id_owner = int.Parse(Session["user_id"].ToString()), id_message = Model.MessageID }))
    {
        <textarea name="text_comment" rows="5" cols="85"></textarea>
        <br />
    <input type="submit" class="AddComment mybutton" value="Додати" />
    }
</fieldset>

@Html.Action("CommentsNovelty", "Novelty", new { id = Model.MessageID })

<p>
    @Html.ActionLink("До списку новин", "News", "Novelty")
</p>

Universal-OSBB/Universal-OSBB/Views/Novelty/FilesMessage.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.File>
<div style="text-align:right">
    @if (Model.Count() > 0)
    {
        <span class="display-label">
            <b>Завантажені файли:</b>
        </span>
        <br>

        <table style="display:inline">

            @foreach (var item in Model)
            {
                <tr>
                    <td align="left" style="text-indent: 0px;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Завантажити", "DownloadFile", "Novelty", new { filename = item.Name }, null)
                    </td>
                </tr>
            }
        </table>
    }
</div>

Universal-OSBB/Universal-OSBB/Views/Novelty/News.cshtml
@{
    Session["menu_item"] = "news";
}
@model IEnumerable<Universal_OSBB.Models.Entities.Message>

@foreach (var item in Model)
{
    <fieldset>
        <legend>@Html.ActionLink(item.Topic, "DetailsNovelty", new { id = item.MessageID })</legend>

        @Html.DisplayFor(modelItem => item.Text)

    <div style="text-align:right">
        @Html.DisplayNameFor(model => model.DatePublication): @Html.DisplayFor(modelItem => item.DatePublication),
        @Html.ActionLink(item.Owner.Surname + " " + item.Owner.Name + " " + item.Owner.MiddleName, "DetailsOwner", "Owner", new { id = item.OwnerID }, null)
    </div>
    </fieldset>
}