Universal-OSBB/Universal-OSBB/Models/Entities/Interview.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Universal_OSBB.Models.Entities
{
    public class Interview
    {
        [Key]
        [HiddenInput(DisplayValue = false)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int InterviewID { get; set; }

        [Required]
        [Display(Name = "Опубліковано")]
        [DataType(DataType.Date)]
        public DateTime DatePublication { get; set; }

        [Required(ErrorMessage = "Введіть тему опитування!")]
        [Display(Name = "Тема")]
        public string Topic { get; set; }

        [Required(ErrorMessage = "Введіть питання!")]
        [Display(Name = "Питання")]
        public string Text { get; set; }


        [Required(ErrorMessage = "Введіть дату завершення опитування!")]
        [Display(Name = "Завершення")]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        [Required]
        public int OwnerID { get; set; }

        public virtual Owner Owner { get; set; }

        public virtual ICollection<Option> Options { get; set; }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.DataVisualization.Charting;
using Universal_OSBB.Models.Context;
using System.Data.Entity;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class ChartController : Controller
    {
        OOABContext db = new OOABContext();
        List<Tuple<int, string>> DatesForTable = new List<Tuple<int, string>>();
        public FileContentResult GetChart(int identificator)
        {
            var dates = new List<Tuple<float, string>>();
            
            List<Option> options = db.Options.Where(id => id.InterviewID == identificator).ToList<Option>();

            int CountOwnerInOSBB = OwnerHelper.GetAllOwners(OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()))).Count();

            foreach (Option option in options)
            {
                int CountOption = db.Results.Where(id => id.OptionID == option.OptionID && id.InterviewID == identificator).Count();
                if (CountOption > 0)
                {
                    float InPercent = (float)CountOption * 100 / CountOwnerInOSBB;
                    dates.Add(new Tuple<float, string>(InPercent, option.Text));
                }
            }

            dates.Sort();
            dates.Reverse();

            DatesForTable.Sort();
            DatesForTable.Reverse();

            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));

            int CountNotVoteOwners = (from o in db.Owners.Where(id => id.OOABID == id_osbb)
                                      join r in db.Results.Where(id => id.InterviewID == identificator)
                                      on o.OwnerID equals r.OwnerID into or
                                      from r in or.DefaultIfEmpty()
                                      where r == null
                                      select r).Count();

            if (CountNotVoteOwners > 0)
            {
                dates.Add(new Tuple<float, string>((float)CountNotVoteOwners * 100 / CountOwnerInOSBB, "Не голосували"));
            }

            var chart = new Chart();
            chart.Width = 700;
            chart.Height = 300;
            chart.BackColor = Color.FromArgb(211, 223, 240);
            chart.BorderlineDashStyle = ChartDashStyle.Solid;
            chart.BackSecondaryColor = Color.White;
            chart.BackGradientStyle = GradientStyle.TopBottom;
            chart.BorderlineWidth = 1;
            chart.Palette = ChartColorPalette.BrightPastel;
            chart.BorderlineColor = Color.FromArgb(26, 59, 105);
            chart.RenderType = RenderType.BinaryStreaming;
            chart.BorderSkin.SkinStyle = BorderSkinStyle.Emboss;
            chart.AntiAliasing = AntiAliasingStyles.All;
            chart.TextAntiAliasingQuality = TextAntiAliasingQuality.Normal;
            chart.Legends.Add(CreateLegend());
            chart.Series.Add(CreateSeries(dates, SeriesChartType.Pie, Color.Red));
            chart.ChartAreas.Add(CreateChartArea());

            var ms = new MemoryStream();
            chart.SaveImage(ms);
            return File(ms.GetBuffer(), @"image/png");
            
        }

        [NonAction]
        public Series CreateSeries(IList<Tuple<float, string>> results, SeriesChartType chartType, Color color)
        {
            var seriesDetail = new Series();
            seriesDetail.Name = "Result Chart";
            seriesDetail.LabelFormat = "N2";
            seriesDetail.IsValueShownAsLabel = true;
            seriesDetail.Color = color;
            seriesDetail.ChartType = chartType;
            seriesDetail.BorderWidth = 2;
            seriesDetail["DrawingStyle"] = "Cylinder";
            seriesDetail["PieDrawingStyle"] = "SoftEdge";
            DataPoint point;

            foreach (var result in results)
            {
                point = new DataPoint();
                point.AxisLabel = result.Item2;
                point.YValues = new double[] { result.Item1 };
                seriesDetail.Points.Add(point);
            }
            seriesDetail.ChartArea = "Result Chart";

            return seriesDetail;
        }

        [NonAction]
        public Legend CreateLegend()
        {
            var legend = new Legend();
            legend.Docking = Docking.Bottom;
            legend.Alignment = StringAlignment.Center;
            legend.BackColor = Color.Transparent;
            legend.Font = new Font(new FontFamily("Trebuchet MS"), 9);
            legend.LegendStyle = LegendStyle.Column;
            legend.Docking = Docking.Right;

            return legend;
        }

        [NonAction]
        public ChartArea CreateChartArea()
        {
            var chartArea = new ChartArea();
            chartArea.BackColor = Color.Transparent;
            chartArea.Name = "Result Chart";
            chartArea.AxisX.IsLabelAutoFit = false;
            chartArea.AxisY.IsLabelAutoFit = false;
            chartArea.AxisX.LabelStyle.Font = new Font("Verdana,Arial,Helvetica,sans-serif", 8F, FontStyle.Regular);
            chartArea.AxisY.LabelStyle.Font = new Font("Verdana,Arial,Helvetica,sans-serif", 8F, FontStyle.Regular);
            chartArea.AxisY.LineColor = Color.FromArgb(64, 64, 64, 64);
            chartArea.AxisX.LineColor = Color.FromArgb(64, 64, 64, 64);
            chartArea.AxisY.MajorGrid.LineColor = Color.FromArgb(64, 64, 64, 64);
            chartArea.AxisX.MajorGrid.LineColor = Color.FromArgb(64, 64, 64, 64);
            chartArea.AxisX.Interval = 1;
            return chartArea;
        }

        public ActionResult ShowResultInTable(int identificator)
        {
            List<Option> options = db.Options.Where(id => id.InterviewID == identificator).ToList<Option>();

            int CountOwnerInOSBB = OwnerHelper.GetAllOwners(OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()))).Count();

            foreach (Option option in options)
            {
                int CountOption = db.Results.Where(id => id.OptionID == option.OptionID && id.InterviewID == identificator).Count();
                DatesForTable.Add(new Tuple<int, string>(CountOption, option.Text));
            }

            DatesForTable.Sort();
            DatesForTable.Reverse();

            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));

            int CountNotVoteOwners = (from o in db.Owners.Where(id => id.OOABID == id_osbb)
                                      join r in db.Results.Where(id => id.InterviewID == identificator)
                                      on o.OwnerID equals r.OwnerID into or
                                      from r in or.DefaultIfEmpty()
                                      where r == null
                                      select r).Count();

            if (CountNotVoteOwners > 0)
            {
                DatesForTable.Add(new Tuple<int, string>(CountNotVoteOwners, "Не голосували"));
            }
            return PartialView(DatesForTable);
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Context;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;
using System.Data.Entity;

namespace Universal_OSBB.Controllers
{
    public class InterviewController : Controller
    {
        OOABContext db = new OOABContext();
        public ActionResult Interviews()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(InterviewHelper.GetAllInterviews(id_osbb));
        }
        public ActionResult CreateInterview()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitCreateInterview(Interview interview, List<string> opt)
        {
            if (opt.Contains(""))
                ModelState.AddModelError("EndDate", "Введіть варіанти відповіді!");


            if (ModelState.IsValid)
            {
                if (interview.EndDate <= DateTime.Now)
                {
                    ModelState.AddModelError("EndDate", "Дата завершення опитування повинна бути більшою за поточну!");
                    return View("CreateInterview");
                }
            
                interview.DatePublication = DateTime.Now;
                interview.OwnerID = int.Parse(Session["user_id"].ToString());
                for (int i = 0; i < opt.Count(); i++)
                {
                    Option TempOption = new Option();
                    TempOption.InterviewID = interview.InterviewID;
                    TempOption.Text = opt[i];
                    db.Options.Add(TempOption);
                }
                db.Interviews.Add(interview);
                db.SaveChanges();

                int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
                return View("Interviews", InterviewHelper.GetAllInterviews(id_osbb));                    
            }
            else
                return View("CreateInterview");
        }

        public ActionResult OptionsInterview(int id)
        {
            return PartialView(InterviewHelper.GetOptionsByInterviewID(id));
        }

        public ActionResult DetailsInterview(int id)
        {
            return View(InterviewHelper.GetInterviewByID(id));
        }

        public ActionResult SubmitVote(string RadioButtonOptionID, int InterviewID)
        {
            Result result = new Result();
            result.OptionID = int.Parse(RadioButtonOptionID);
            result.InterviewID = InterviewID;
            result.OwnerID = int.Parse(Session["user_id"].ToString());
            db.Results.Add(result);
            db.SaveChanges();
            return View("DetailsInterview", InterviewHelper.GetInterviewByID(InterviewID));
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class OwnerController : Controller
    {
        public ActionResult DetailsOwner(int id)
        {
            return View(OwnerHelper.GetOwnerById(id));
        }

        public ActionResult StatementToHead()
        {
            int id_owner = Convert.ToInt32(Session["user_id"].ToString());
            ViewBag.Owner = OwnerHelper.GetOwnerById(id_owner).FullName;
            return View();
        }

        public ActionResult CreateStatementToHead(string MainTextStatement)
        {
            if (MainTextStatement == "")
                ModelState.AddModelError("MainText", "Введіть текст заяви!");
            if (!ModelState.IsValid)
            {
                int id_owner = Convert.ToInt32(Session["user_id"].ToString());
                ViewBag.Owner = OwnerHelper.GetOwnerById(id_owner).FullName;
                return View("StatementToHead");
            }
                
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()));
            Owner head = OwnerHelper.GetHeadOfOOAB(id_osbb);
            string FullNameHead = head.Surname + " " + head.Name[0] + "." + head.MiddleName[0] + ".";
            OOAB osbb = OwnerHelper.GetOSBBById(id_osbb);
            Owner sender = OwnerHelper.GetOwnerById(int.Parse(Session["user_id"].ToString()));
            string FullNameOwner = sender.Surname + " " + sender.Name + " " + sender.MiddleName;
            return File(WordHelper.CreateStatementToHead(osbb.Name, FullNameHead, FullNameOwner, MainTextStatement, DateTime.Now),
                    "application/octet-stream", "Заява_голові_ОСББ.docx");
        }

        public ActionResult Phones(int id)
        {
            return PartialView(OwnerHelper.GetPhonesById(id));
        }

        public ActionResult PropertiesOwner(int id)
        {
            return PartialView(OwnerHelper.GetPropertiesByID(id));
        }

        public ActionResult OwnersHead()
        {
            //для пошуку по будинку та квартирі
            int selectedIndex = 1;
            SelectList houses = new SelectList(PropertyHelper.GetHousesByIdOSBB(OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()))), "HouseID", "Name", selectedIndex);
            ViewBag.Houses = houses;
            SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(selectedIndex), "RoomID", "Name");
            ViewBag.Rooms = rooms;

            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;

            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return View(OwnerHelper.GetAllOwners(owner.OOABID));
        }

        public ActionResult Owners()
        {
            //для пошуку по будинку та квартирі
            int selectedIndex = 1;
            SelectList houses = new SelectList(PropertyHelper.GetHousesByIdOSBB(OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()))), "HouseID", "Name", selectedIndex);
            ViewBag.Houses = houses;
            SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(selectedIndex), "RoomID", "Name");
            ViewBag.Rooms = rooms;

            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(OwnerHelper.GetAllActiveOwners(id_osbb));
        }

        public ActionResult SearchOwners(int id_osbb, string surname, string name)
        {
            List<Owner> searchedowners;
            searchedowners = OwnerHelper.SearchOwnersBySurnameName(id_osbb, surname, name);
            return PartialView(searchedowners);
        }

        public ActionResult SearchOwnersByHouseRoomHelper(int id)
        {
            return PartialView(PropertyHelper.GetRoomsByIdHouse(id).ToList());
        }

        public ActionResult SearchOwnersByHouseRoom(int room)
        {
            return PartialView("SearchOwners", OwnerHelper.SearchOwnersByHouseRoom(room).ToList());
        }

        public ActionResult DoNoActive(int id)
        {
            OwnerHelper.MakeNotActive(id);
            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return RedirectToAction("OwnersHead");
        }

        public ActionResult DoActive(int id)
        {
            OwnerHelper.MakeActive(id);
            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return RedirectToAction("OwnersHead");
        }

        public ActionResult EditOwner(int id_owner)
        {
            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;
            return View(OwnerHelper.GetOwnerById(id_owner));
        }

        public ActionResult SaveChangeOwner(Owner owner)
        {
            if(ModelState.IsValid)
            {
                OwnerHelper.UpdateChangeOwner(owner);
                ViewBag.Result = "Інформація збережена!";        
                return View("AdditionSuccessful");
            }
            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;
            return View("EditOwner", OwnerHelper.GetOwnerById(owner.OwnerID));
        }
    }
}

Universal-OSBB/Universal-OSBB/Views/Interview/CreateInterview.cshtml
@model Universal_OSBB.Models.Entities.Interview

@using (Html.BeginForm("SubmitCreateInterview", "Interview"))
{
    <fieldset>
        <legend>Створення опитування</legend>
        <p>
            @Html.ValidationSummary()
        </p>

        <span class="editor-label">
            @Html.LabelFor(model => model.Topic):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Topic)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Text):
        </span>
        <span class="editor-field">
            @Html.TextAreaFor(model => model.Text, rows: 4, columns: 80, htmlAttributes: null)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.EndDate):
            @Html.EditorFor(model => model.EndDate)
        </span>
        <br>
        <br>
        <div id="DynamicExtraFieldsContainer">
            <div id="DynamicExtraField">
                <label for=" dynamicoptionfield">Варіант відповіді:</label>
                <br>
                <input name="opt" sty/>
            </div>
            <input type="button" id="AddOptionButton" value="Додати варіант">
        </div>

        <p>
            <input class="mybutton" type="submit" value="Опублікувати" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("До списку опитувань", "Interviews", "Interview")
</div>

Universal-OSBB/Universal-OSBB/Views/Interview/DetailsInterview.cshtml
@model Universal_OSBB.Models.Entities.Interview
@using Universal_OSBB.Models.Repository
<fieldset>
    @if (InterviewHelper.IsVoted(Model.InterviewID, int.Parse(Session["user_id"].ToString())) || Model.EndDate < DateTime.Now)
    {
        <legend>Результати голосування "@Model.Topic"</legend>
        <p>@Model.Text (опитування проводиться до @Model.EndDate.Date.ToShortDateString())</p>
        
        <div style="text-align:center">
            <img src=@Url.Action("GetChart", "Chart", new { identificator = Model.InterviewID }) /> <br />
        </div>
        @Html.Action("ShowResultInTable", "Chart", new { identificator = Model.InterviewID });
    }
    else
    {
        <legend>@Model.Topic</legend>
        <div class="display-label">
            @Html.DisplayFor(model => model.Text)
        </div>
        @Html.Action("OptionsInterview", "Interview", new { id = Model.InterviewID })
    }
    <div class="display-label" style="text-align:right">
        @Html.DisplayNameFor(model => model.DatePublication): @Html.DisplayFor(modelItem => modelItem.DatePublication),
        @Html.ActionLink(Model.Owner.Surname + " " + Model.Owner.Name + " " + Model.Owner.MiddleName, "DetailsOwner", "Owner", new { id = Model.OwnerID }, null)
    </div>
</fieldset>
<p>
    @Html.ActionLink("До списку опитувань", "Interviews", "Interview")
</p>

Universal-OSBB/Universal-OSBB/Views/Interview/Interviews.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Interview>

@{
    Session["menu_item"] = "interviews";
}
@foreach (var item in Model)
{
    <fieldset>
        <legend>@Html.ActionLink(item.Topic, "DetailsInterview", new { id = item.InterviewID })</legend>

        @Html.DisplayFor(modelItem => item.Text)
        <div style="text-align:right">
            @Html.DisplayNameFor(model => model.DatePublication):
            @Html.DisplayFor(modelItem => item.DatePublication),
            @Html.ActionLink(item.Owner.Surname + " " + item.Owner.Name + " " + item.Owner.MiddleName, "DetailsOwner", "Owner", new { id = item.OwnerID }, null)
        </div>
    </fieldset>
}

Universal-OSBB/Universal-OSBB/Views/Interview/OptionsInterview.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Option>

@using (Html.BeginForm("SubmitVote", "Interview", FormMethod.Post))
{
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.RadioButton("RadioButtonOptionID", item.OptionID.ToString(), new { id = "RadioButtonOption" }) @Html.DisplayFor(modelItem => item.Text)
                    @Html.TextBox("InterviewID", item.InterviewID, new { style = "display:none" })
                </td>
            </tr>
        }
    </table>
    <p>
        <input class="mybutton" type="submit" name="vote" value="Голосувати" />
    </p>
}