Universal-OSBB/Universal-OSBB/Models/Entities/Reports/MonthlyFee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;

namespace Universal_OSBB.Models.Entities.Reports
{
    public class MonthlyFee
    {
        [Display(Name = "Місяць")]
        public string NameMonth
        {
            get
            {
                return new DateTime(2016, Month, 1).ToString("MMMM", new CultureInfo("uk-UA"));
            } 
        }

        [Display(Name = "Номер місяця")]
        public int Month { get; set; }

        [Display(Name = "Рік")]
        public int Year { get; set; }

        [Display(Name = "Абонплата")]
        public decimal Payment { get; set; }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/FinanceController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Entities.Reports;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class FinanceController : Controller
    {
        public ActionResult CostPlanning()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(FinanceHelper.GetFutureCostPlanning(id_osbb));
        }
        public ActionResult CostPlanningOwners()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(FinanceHelper.GetFutureCostPlanning(id_osbb));
        }

        public ActionResult PaymentForRooms()
        {
            List<Receipt> receipts = FinanceHelper.GetReceiptsForRooms(OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString())), int.Parse(Session["user_id"].ToString()));
            decimal total = 0;
            for (int i = 0; i < receipts.Count(); i++)
                total += receipts[i].Payment;
            ViewBag.Total = total;
            return View(receipts);
        }

        public ActionResult TotalPaymentForRoom(int id_room, int id_osbb, int id_owner)
        {
            decimal TotalPaymentForRoom = FinanceHelper.TotalPaymentByIdRoom(id_room, id_osbb, id_owner);
            ViewBag.TotalForRoom = TotalPaymentForRoom;
            return PartialView();
        }

        public ActionResult CreatePlannedProduct()
        {
            FillViewBagLists();
            return View();
        }

        public ActionResult EditPlannedProduct(int id_product)
        {
            FillViewBagLists();
            return View(FinanceHelper.GetProductById(id_product));
        }

        public ActionResult DetailsPlannedProduct(int id_product)
        {
            return View(FinanceHelper.GetProductById(id_product));
        }   

        public ActionResult DeletePlannedProduct(int id_product)
        {
            FinanceHelper.DeleteProductById(id_product);
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View("CostPlanning", FinanceHelper.GetFutureCostPlanning(id_osbb));    

        }

        public ActionResult SaveEditPlannedPurchase(Cost product)
        {
            if (product.DateEnd != null && product.DatePurchase > product.DateEnd)
                ModelState.AddModelError("DatePurchase", "Оберіть коректні межі періоду придбання!");
            if (ModelState.IsValid)
            {
                if (product.DatePurchase != null)
                {
                    DateTime now = DateTime.Now;
                    DateTime min_date;
                    if (now.Month == 12)
                        min_date = new DateTime(now.Year + 1, 1, 1);
                    else
                        min_date = new DateTime(now.Year, now.Month + 1, 1);

                    if (product.DatePurchase < min_date)
                        ModelState.AddModelError("DatePurchase", "Планувати закупівлі можна тільки на майбутні періоди " + 
                            "(не раніше, ніж з першого числа наступного місяця)!");
                }
                if (ModelState.IsValid)
                {
                    FinanceHelper.UpdateProduct(product);
                    int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
                    ViewBag.Result = "Інформація про заплановані витрати збережена!";
                    return View("AdditionSuccessful");
                }
                else
                {
                    FillViewBagLists();
                    return View("EditPlannedProduct", product);
                }
            }
            else
            {
                FillViewBagLists();
                return View("EditPlannedProduct", product);
            }

        }
        

        public ActionResult AddPlannedPurchase(Cost product)
        {
            if (product.DateEnd != null && product.DatePurchase > product.DateEnd)
                ModelState.AddModelError("DatePurchase", "Оберіть коректні межі періоду придбання!");
            if (ModelState.IsValid)
            {
                DateTime now = DateTime.Now;
                DateTime min_date;
                if (now.Month == 12)
                    min_date = new DateTime(now.Year + 1, 1, 1);
                else
                    min_date = new DateTime(now.Year, now.Month + 1, 1);

                if (product.DatePurchase < min_date)
                    ModelState.AddModelError("DatePurchase", "Планувати закупівлі можна тільки на майбутні періоди " + 
                        "(не раніше, ніж з першого числа наступного місяця)!");
                
                if (ModelState.IsValid)
                {
                    product.OOABID = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
                    FinanceHelper.AddPurchasedProduct(product);
                    ViewBag.Result = "Інформація про заплановані витрати збережена!";
                    return View("AdditionSuccessful");
                }
                else
                {
                    FillViewBagLists();
                    return View("CreatePlannedProduct", product);
                }
            }
            else
            {
                FillViewBagLists();
                return View("CreatePlannedProduct", product);
            }
        }

        public void FillViewBagLists()
        {
            List<Measurement> measurements = FinanceHelper.GetMeasurements();
            SelectList list_measurements = new SelectList(measurements, "MeasurementID", "Name");
            if (list_measurements.Count() > 0)
                list_measurements.First().Selected = true;
            ViewBag.Measurements = list_measurements;
        }
        public ActionResult SpentMoneySearch()
        {
            return View();
        }

        public ActionResult AllSpentMoney()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            List<Cost> spent_money = FinanceHelper.GetSpentMoney(id_osbb, null, null);
            ViewBag.TotalSum = FinanceHelper.TotalSpentMoney(spent_money);
            return View("SpentMoney", spent_money);
        }

        public ActionResult SpentMoney(SpentMoneyReport dates)
        {
            if (dates.DateFrom != null && dates.DateTo != null && dates.DateFrom > dates.DateTo)
                ModelState.AddModelError("DateFrom", "Оберіть коректні межі звітного періоду!");
            if (ModelState.IsValid)
            {
                int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));

                List<Cost> spent_money = new List<Cost>();

                ViewBag.Message = "в період з " + dates.DateFrom.Date.ToString("d") + " до " + dates.DateTo.Date.ToString("d");
                spent_money = FinanceHelper.GetSpentMoney(id_osbb, dates.DateFrom, dates.DateTo);
                ViewBag.TotalSum = FinanceHelper.TotalSpentMoney(spent_money);

                return View(spent_money);
            }
            else
                return View("SpentMoneySearch");
        }

        public ActionResult MonthlyFee()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(FinanceHelper.MonthlyFeesBy12(id_osbb, DateTime.Now.Month, DateTime.Now.Year));
        }

        public ActionResult CreateReceipt()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
  
            List<House> houses = PropertyHelper.GetHousesByIdOSBB(id_osbb);
            SelectList list_houses = new SelectList(houses, "HouseID", "Name");
            ViewBag.Houses = list_houses;
            
            SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(houses.First().HouseID), "RoomID", "Name");
            ViewBag.Rooms = rooms;

            return View();
        }

        public ActionResult ListRooms(int id)
        {
            return PartialView(PropertyHelper.GetRoomsByIdHouse(id));
        }

        public ActionResult AddReceipt(Receipt receipt)
        {
            if(receipt.RoomID == 0)
            {
                ModelState.AddModelError("RoomID", "Оберіть приміщення!");
            }
            if (receipt.DatePayment > DateTime.Now)
            {
                ModelState.AddModelError("DatePayment", "Дата сплати не повинна перевищувати сьогоднішню дату!");
            }
            if (ModelState.IsValid)
            {

                FinanceHelper.AddReceipt(receipt);
                ViewBag.Result = "Інформація про сплату коштів збережена!";
                return View("AdditionSuccessful");
            }
            else
            {
                int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
                List<House> houses = PropertyHelper.GetHousesByIdOSBB(id_osbb);
                SelectList list_houses = new SelectList(houses, "HouseID", "Name");
                ViewBag.Houses = list_houses;

                SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(houses.First().HouseID), "RoomID", "Name");
                ViewBag.Rooms = rooms;
                return View("CreateReceipt");
            }
        }

        public ActionResult CurrentCosts()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(FinanceHelper.GetCurrentCostPlanning(id_osbb));
        }

        [HttpPost]

Universal-OSBB/Universal-OSBB/Views/Finance/CostPlanning.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Cost>

<fieldset>
    <legend>Заплановані витрати</legend>
    <p>
        @Html.ActionLink("Додати", "CreatePlannedProduct")
    </p>
    @if(Model.Count() > 0 )
    { 
    <table class="list_table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>   
            <th>
                @Html.DisplayNameFor(model => model.Payment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePurchase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
   
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(Html.DisplayFor(modelItem => item.Name) + "",
                 "EditPlannedProduct", new { id_product = item.CostID })
                </td>
                <td class="number">
                    @Html.DisplayFor(modelItem => item.Payment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePurchase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEnd)
                </td>
                <td class="invisible">
                    @Html.ActionLink("Видалити", "DeletePlannedProduct", new { id_product = item.CostID })
                </td>
            </tr>
        }

    </table>
    }
    else
    {
       <p>Заплановані витрати відсутні</p>
    }
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/CostPlanningOwners.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Cost>

<fieldset>
    <legend>Заплановані витрати</legend>
    @if (Model.Count() > 0)
    {
        <table class="list_table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Payment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatePurchase)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateEnd)
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(Html.DisplayFor(modelItem => item.Name) + "",
                 "DetailsPlannedProduct", new { id_product = item.CostID })
                    </td>
                    <td class="number">
                        @Html.DisplayFor(modelItem => item.Payment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatePurchase)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateEnd)
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>Заплановані витрати відсутні</p>
    }
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/CreateReceipt.cshtml
@model Universal_OSBB.Models.Entities.Receipt

@using (Html.BeginForm("AddReceipt", "Finance", FormMethod.Post))
{
   
    <fieldset>
        <legend>Сплата коштів</legend>

        <p>
            @Html.ValidationSummary()
        </p>

        <span class="editor-label">
            Будинок:
        </span>
        <span class="editor-field">
            @Html.DropDownList("HouseID", ViewBag.Houses as SelectList, new { id = "HouseID" })
        </span>
        <br>

        <span class="editor-label">
            Приміщення:
        </span>
        <span class="editor-field">
            @Html.DropDownList("RoomID", ViewBag.Rooms as SelectList, new { id = "RoomID" })
        </span>

        @section scripts
        {
            <script type="text/javascript">

                $(function () {

                    $('#HouseID').change(function () {
                        // получаем выбранный id
                        var id = $(this).val();

                        $.ajax({
                            type: 'GET',
                            url: '@Url.Action("ListRooms")/' + id,
                            success: function (data) {
                                // заменяем содержимое присланным частичным представлением
                                $('#RoomID').replaceWith(data);
                            }

                        });
                    });
                })
            </script>
        }
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.DatePayment):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.DatePayment)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Payment):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Payment)
        </span>
        <br>

        

        <p>
            <input class="mybutton" type="submit" value="Зберегти" />
        </p>
</fieldset>
}

Universal-OSBB/Universal-OSBB/Views/Finance/CurrentCosts.cshtml
@model List<Universal_OSBB.Models.Entities.Cost>

@using Universal_OSBB.Models.Repository;

@{
    Session["menu_item"] = "costs";
}

<fieldset>
    <legend>Витрати поточного місяця</legend>
    @using (Html.BeginForm("SaveCurrentCosts", "Finance", FormMethod.Post))
    {
        <table class="list_table">
            <tr>
                <th>
                    Найменування
                </th>
                <th>
                    Вартість, грн
                </th>
                <th>
                    Запланована дата придбання
                </th>
                <th>
                    Кінцева дата придбання
                </th>
                <th>
                    Виконання
                </th>
            </tr>

            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(model => model[i].CostID)
                    <td>
                        @Html.ActionLink(@Html.DisplayFor(model => model[i].Name) + "", "DetailsCurrentCost",
                        new { id_product = Model[i].CostID })
                    </td>
                    <td class="number">
                        @Html.DisplayFor(model => model[i].Payment)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model[i].DatePurchase)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model[i].DateEnd)
                    </td>
                    <td>
                        @if (Model[i].DateFactual != null)
                        { 
                            @Html.CheckBox("IsDone", true, new { @disabled = "disabled" })
                        }
                        else
                        {
                            if(OwnerHelper.IsHead(Convert.ToInt32(Session["user_id"].ToString())))
                            {
                                @Html.EditorFor(model => model[i].IsDone)
                            }
                            else
                            {
                                @Html.DisplayFor(model => model[i].IsDone)
                            }
                        }
                    </td>
                </tr>
            }

        </table>
        if(OwnerHelper.IsHead(Convert.ToInt32(Session["user_id"].ToString())))
        { 
            <p>
                <input class="mybutton" type="submit" value="Зберегти" />
            </p>
        }
    }
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/Deptors.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Room>

<fieldset>
    <legend>Боржники</legend>
    <table class="list_table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.House.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dept)
            </th>
            <th>
                Власники
            </th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.House.Name)
            </td>
            <td>
                @Html.ActionLink(Html.DisplayFor(modelItem => item.Name).ToString(),
         "DetailsRoom", "Property", new { id_room = item.RoomID }, null)
            </td>
            <td class="number">
                @Html.DisplayFor(modelItem => item.Dept)
            </td>
            <td>
                @Html.Action("DeptorsOwners", "Finance", new { id_room = item.RoomID })
            </td>
        </tr>
    }

    </table>
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/DeptorsOwners.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Owner>


@foreach (var item in Model) {

    @Html.ActionLink(
            Html.DisplayFor(modelItem => item.Surname) + " " +

            Html.DisplayFor(modelItem => item.Name) + " " +

            Html.DisplayFor(modelItem => item.MiddleName), "DetailsOwner", "Owner", new { id = item.OwnerID }, null)
    <br>
}

Universal-OSBB/Universal-OSBB/Views/Finance/DetailsCurrentCost.cshtml
@model Universal_OSBB.Models.Entities.Cost

<fieldset>
    <legend>Поточні витрати</legend>

    <span class="display-label">
         @Html.DisplayNameFor(model => model.Name):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Name)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.Description):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Description)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.Measurement):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Measurement.Name)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.Amount):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Amount)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.Price):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Price)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.Payment):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.Payment)
    </span>
    <br>

    <span class="display-label">
        @Html.DisplayNameFor(model => model.DatePurchase):
    </span>
    <span class="display-field">
        @Html.DisplayFor(model => model.DatePurchase)
    </span>
    <br>
    @if(Model.DateEnd != null)
    {
        <span class="display-label">
            @Html.DisplayNameFor(model => model.DateEnd):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.DateEnd)
        </span>
        <br>
    }

    <span class="display-label">
        @Html.DisplayNameFor(model => model.DateFactual):
    </span>
    <span class="display-field">
        @if (Model.DateFactual != null)
        { 
            @Html.DisplayFor(model => model.DateFactual)
        }
        else
        {
            <text>ще не придбано</text>
        }  
    </span>

</fieldset>
<p>
    @Html.ActionLink("До списку поточних витрат", "CurrentCosts")
</p>

Universal-OSBB/Universal-OSBB/Views/Finance/EditPlannedProduct.cshtml
@model Universal_OSBB.Models.Entities.Cost

<fieldset>
    <legend>Редагування запланованих витрат</legend>
    @using (Html.BeginForm("SaveEditPlannedPurchase", "Finance", FormMethod.Post))
    {
        <p>
            @Html.ValidationSummary()
        </p>

        @Html.HiddenFor(model => model.CostID)

        <span class="editor-label">
            @Html.LabelFor(model => model.Name):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Name)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Description):
        </span>
        <br>
        <span class="editor-field">
            @Html.TextAreaFor(model => model.Description)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Measurement):
        </span>
        <span class="editor-field">
            @Html.DropDownList("MeasurementID", ViewBag.Measurements as SelectList)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Amount):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Amount)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.Price):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Price)
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.DatePurchase):
        </span>
        <span class="editor-field">
            <input name="DatePurchase" type="date" value="@Model.DatePurchase.ToString("yyyy-MM-dd")">
        </span>
        <br>

        <span class="editor-label">
            @Html.LabelFor(model => model.DateEnd):
        </span>
        <span class="editor-field">
            @if (Model.DateEnd != null)
            {
                DateTime date = (DateTime)Model.DateEnd;
                <input name="DateEnd" type="date" value="@date.ToString("yyyy-MM-dd")">
            }
            else
            {
                @Html.EditorFor(model => model.DateEnd)
            }
        </span>

        <p>
            <input class="mybutton" type="submit" value="Зберегти" />
        </p>

    }
</fieldset>
<div>
    @Html.ActionLink("До списку запланованих витрат", "CostPlanning")
</div>

Universal-OSBB/Universal-OSBB/Views/Finance/ListRooms.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Room>
@if(Model.Count() > 0)
{
    <select id="RoomID" name="RoomID">
        @foreach (var item in Model)
        {
            <option value="@item.RoomID">@item.Name</option>
        }
    </select>
}
else
{
    <text>у вибраному будинку не зареєстровано приміщень</text>
}

Universal-OSBB/Universal-OSBB/Views/Finance/MonthlyFee.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Reports.MonthlyFee>
@using Universal_OSBB.Models.Repository;

<fieldset>
    <legend>Абонплата на 12 місяців</legend>
    <table class="list_table" style="width:50%; margin: 0 auto;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment), <br>грн/м<sup>2</sup>
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameMonth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td class="number">
                    @Html.DisplayFor(modelItem => item.Payment)
                </td>
            </tr>
        }

    </table>
    
    @if(OwnerHelper.IsHead(Convert.ToInt32(Session["user_id"].ToString())))
    {
        <span>
            Якщо абонплата занадто висока, @Html.ActionLink("відредагуйте", "CostPlanning", "Finance") дейкі заплановані витрати
        </span>
    }
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/PaymentForRooms.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Receipt>

@{
    Session["menu_item"] = "payments";
}

@using Universal_OSBB.Models.Repository;
<fieldset>
    <legend>Сплата за приміщення</legend>
    <span class="editor-label" style="margin-left:130px">
        за період з <input type="date" name="startcalendar">
        по <input type="date" name="endcalendar">
    </span>
    <table class="sub_list">
        <tr>
            <td align="center">
                <strong>Дата сплати</strong>
            </td>
            <td align="center">
                <strong>Сума, грн</strong>
            </td>
        </tr>
    </table>
    @{String Name = ""; int index = 0;}
    @foreach (var item in Model)
    {
        <table class="sub_list">
            <tr>
                @if (String.Compare(item.Room.Name, Name) != 0)
                {
                    <td colspan="2" align="center" style="background-color:antiquewhite">
                        @Html.ActionLink(item.Room.Name, "DetailsRoom", "Property", new { id_room = item.RoomID }, null)
                        @{Name = item.Room.Name;}
                    </td>
                }
            </tr>
            @if (item.Payment == 0)
            {
                <tr>
                    <td align="center" colspan="2">
                        Немає даних про сплату за приміщення
                    </td>
                </tr>
                index++;
            }
            else
            {
                <tr>
                    <td align="center">
                        @Html.DisplayFor(modelItem => item.DatePayment)
                    </td>
                    <td align="right">
                        @Html.DisplayFor(modelItem => item.Payment)
                    </td>
                </tr>
                index++;
                if (index != Model.Count())
                {
                    if (String.Compare(Model.ElementAt(index).Room.Name, item.Room.Name) != 0)
                    {
                        @Html.Action("TotalPaymentForRoom", "Finance", new { id_room = item.RoomID, id_osbb = OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString())), id_owner = int.Parse(Session["user_id"].ToString()) });
                    }
                }
                else
                {
                    @Html.Action("TotalPaymentForRoom", "Finance", new { id_room = item.RoomID, id_osbb = OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString())), id_owner = int.Parse(Session["user_id"].ToString()) });
                }
            }
        </table>
    }
    <table class="sub_list">
        <tr>
            <td align="right">
                <strong>Всього:</strong>
            </td>
            <td align="right">
                <strong>@String.Format("{0:N2}",@ViewBag.Total)</strong>
            </td>
        </tr>
    </table>
</fieldset>

Universal-OSBB/Universal-OSBB/Views/Finance/TotalPaymentForRoom.cshtml
<tr>
    <td align="right">
        <strong>Всього за приміщення:</strong>
    </td>
    <td align="right">
        <strong>@String.Format("{0:N2}", ViewBag.TotalForRoom)</strong>
    </td>
</tr>