Universal-OSBB/Universal-OSBB/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Context;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;
using System.Data.Entity;

namespace Universal_OSBB.Controllers
{
    public class InterviewController : Controller
    {
        OOABContext db = new OOABContext();
        public ActionResult Interviews()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(InterviewHelper.GetAllInterviews(id_osbb));
        }
        public ActionResult CreateInterview()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitCreateInterview(Interview interview, List<string> opt)
        {
            if (opt.Contains(""))
                ModelState.AddModelError("EndDate", "Введіть варіанти відповіді!");


            if (ModelState.IsValid)
            {
                if (interview.EndDate <= DateTime.Now)
                {
                    ModelState.AddModelError("EndDate", "Дата завершення опитування повинна бути більшою за поточну!");
                    return View("CreateInterview");
                }
            
                interview.DatePublication = DateTime.Now;
                interview.OwnerID = int.Parse(Session["user_id"].ToString());
                for (int i = 0; i < opt.Count(); i++)
                {
                    Option TempOption = new Option();
                    TempOption.InterviewID = interview.InterviewID;
                    TempOption.Text = opt[i];
                    db.Options.Add(TempOption);
                }
                db.Interviews.Add(interview);
                db.SaveChanges();

                int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
                return View("Interviews", InterviewHelper.GetAllInterviews(id_osbb));                    
            }
            else
                return View("CreateInterview");
        }

        public ActionResult OptionsInterview(int id)
        {
            return PartialView(InterviewHelper.GetOptionsByInterviewID(id));
        }

        public ActionResult DetailsInterview(int id)
        {
            return View(InterviewHelper.GetInterviewByID(id));
        }

        public ActionResult SubmitVote(string RadioButtonOptionID, int InterviewID)
        {
            Result result = new Result();
            result.OptionID = int.Parse(RadioButtonOptionID);
            result.InterviewID = InterviewID;
            result.OwnerID = int.Parse(Session["user_id"].ToString());
            db.Results.Add(result);
            db.SaveChanges();
            return View("DetailsInterview", InterviewHelper.GetInterviewByID(InterviewID));
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class OwnerController : Controller
    {
        public ActionResult DetailsOwner(int id)
        {
            return View(OwnerHelper.GetOwnerById(id));
        }

        public ActionResult StatementToHead()
        {
            int id_owner = Convert.ToInt32(Session["user_id"].ToString());
            ViewBag.Owner = OwnerHelper.GetOwnerById(id_owner).FullName;
            return View();
        }

        public ActionResult CreateStatementToHead(string MainTextStatement)
        {
            if (MainTextStatement == "")
                ModelState.AddModelError("MainText", "Введіть текст заяви!");
            if (!ModelState.IsValid)
            {
                int id_owner = Convert.ToInt32(Session["user_id"].ToString());
                ViewBag.Owner = OwnerHelper.GetOwnerById(id_owner).FullName;
                return View("StatementToHead");
            }
                
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()));
            Owner head = OwnerHelper.GetHeadOfOOAB(id_osbb);
            string FullNameHead = head.Surname + " " + head.Name[0] + "." + head.MiddleName[0] + ".";
            OOAB osbb = OwnerHelper.GetOSBBById(id_osbb);
            Owner sender = OwnerHelper.GetOwnerById(int.Parse(Session["user_id"].ToString()));
            string FullNameOwner = sender.Surname + " " + sender.Name + " " + sender.MiddleName;
            return File(WordHelper.CreateStatementToHead(osbb.Name, FullNameHead, FullNameOwner, MainTextStatement, DateTime.Now),
                    "application/octet-stream", "Заява_голові_ОСББ.docx");
        }

        public ActionResult Phones(int id)
        {
            return PartialView(OwnerHelper.GetPhonesById(id));
        }

        public ActionResult PropertiesOwner(int id)
        {
            return PartialView(OwnerHelper.GetPropertiesByID(id));
        }

        public ActionResult OwnersHead()
        {
            //для пошуку по будинку та квартирі
            int selectedIndex = 1;
            SelectList houses = new SelectList(PropertyHelper.GetHousesByIdOSBB(OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()))), "HouseID", "Name", selectedIndex);
            ViewBag.Houses = houses;
            SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(selectedIndex), "RoomID", "Name");
            ViewBag.Rooms = rooms;

            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;

            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return View(OwnerHelper.GetAllOwners(owner.OOABID));
        }

        public ActionResult Owners()
        {
            //для пошуку по будинку та квартирі
            int selectedIndex = 1;
            SelectList houses = new SelectList(PropertyHelper.GetHousesByIdOSBB(OwnerHelper.GetIdOSBBByIdOwner(int.Parse(Session["user_id"].ToString()))), "HouseID", "Name", selectedIndex);
            ViewBag.Houses = houses;
            SelectList rooms = new SelectList(PropertyHelper.GetRoomsByIdHouse(selectedIndex), "RoomID", "Name");
            ViewBag.Rooms = rooms;

            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(OwnerHelper.GetAllActiveOwners(id_osbb));
        }

        public ActionResult SearchOwners(int id_osbb, string surname, string name)
        {
            List<Owner> searchedowners;
            searchedowners = OwnerHelper.SearchOwnersBySurnameName(id_osbb, surname, name);
            return PartialView(searchedowners);
        }

        public ActionResult SearchOwnersByHouseRoomHelper(int id)
        {
            return PartialView(PropertyHelper.GetRoomsByIdHouse(id).ToList());
        }

        public ActionResult SearchOwnersByHouseRoom(int room)
        {
            return PartialView("SearchOwners", OwnerHelper.SearchOwnersByHouseRoom(room).ToList());
        }

        public ActionResult DoNoActive(int id)
        {
            OwnerHelper.MakeNotActive(id);
            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return RedirectToAction("OwnersHead");
        }

        public ActionResult DoActive(int id)
        {
            OwnerHelper.MakeActive(id);
            Owner owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return RedirectToAction("OwnersHead");
        }

        public ActionResult EditOwner(int id_owner)
        {
            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;
            return View(OwnerHelper.GetOwnerById(id_owner));
        }

        public ActionResult SaveChangeOwner(Owner owner)
        {
            if(ModelState.IsValid)
            {
                OwnerHelper.UpdateChangeOwner(owner);
                ViewBag.Result = "Інформація збережена!";        
                return View("AdditionSuccessful");
            }
            SelectList types = new SelectList(OwnerHelper.GetTypesOfOwners(), "TypeOwnerID", "Name");
            ViewBag.Types = types;
            return View("EditOwner", OwnerHelper.GetOwnerById(owner.OwnerID));
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Repository;

namespace Universal_OSBB.Controllers
{
    public class PropertyController : Controller
    {
        public ActionResult Rooms()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"]));
            return View(PropertyHelper.GetAllRooms(id_osbb));
        }

        public ActionResult CreateRoom()
        {
            FillViewBagLists();
            return View();
        }

        public ActionResult CreateHouse()
        {
            return View();
        }

        public ActionResult Houses()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            return View(PropertyHelper.GetHousesByIdOSBB(id_osbb));
        }

        public ActionResult DetailsRoom(int id_room)
        {
            ViewBag.Dept = FinanceHelper.DeptOfRoom(id_room);
            return View(PropertyHelper.GetRoomById(id_room));
        }

        public ActionResult OwnersOfRoom(int id_room)
        {
            return PartialView(PropertyHelper.GetOwnersById(id_room));
        }
        public ActionResult AddOwnerToRoom(int id_room)
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));

            ViewBag.Id_room = id_room;
            return PartialView(OwnerHelper.GetPossibleOwners(id_osbb, id_room));
        }

        public ActionResult SubmitOwnerToRoom(string value, int id_room)
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"]));
            int? id_owner = OwnerHelper.IsPossibleOwner(value, id_osbb, id_room);
            if(id_owner == null)
                TempData["Error"] = "Оберіть власника зі списку!";
            else
            {
                PropertyHelper.AddOwnerToRoom(id_room, (int)id_owner);
            }
            return RedirectToAction("DetailsRoom", new { id_room = id_room });
        }
        public ActionResult DeleteOwner(int id_room, int id_owner)
        {
            PropertyHelper.DeleteOwner(id_room, id_owner);

            return RedirectToAction("DetailsRoom", new { id_room = id_room });
        }
        public ActionResult AddHouse(House new_house)
        {
            new_house.OOABID = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            if (ModelState.IsValid)
            {
                PropertyHelper.AddHouse(new_house);
                ViewBag.Result = "Будинок успішно зареєстровано!";
                return View("AdditionSuccessful");
            }
            else
            {
                return View("CreateHouse");
            }
        }

        public ActionResult AddRoom(Room new_room)
        {
            if (ModelState.IsValid)
            {
                PropertyHelper.AddRoom(new_room);
                ViewBag.Result = "Приміщення успішно зареєстровано!";
                return View("AdditionSuccessful");
            }
            else
            {
                FillViewBagLists();
                return View("CreateRoom");
            }
        } 

        public void FillViewBagLists()
        {
            int id_osbb = OwnerHelper.GetIdOSBBByIdOwner(Convert.ToInt32(Session["user_id"].ToString()));
            List<House> houses = PropertyHelper.GetHousesByIdOSBB(id_osbb);
            SelectList list_houses = new SelectList(houses, "HouseID", "Name");
            if (list_houses.Count() > 0)
                list_houses.First().Selected = true;
            ViewBag.Houses = list_houses;

            SelectList states = new SelectList(PropertyHelper.GetRoomStates(), "StateRoomID", "State");
            ViewBag.States = states;
        }
    }
}

Universal-OSBB/Universal-OSBB/Controllers/UserController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal_OSBB.Models.Entities;
using Universal_OSBB.Models.Entities.Registration;
using Universal_OSBB.Models.Repository;
using Universal_OSBB.Mappers;

namespace Universal_OSBB.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Registration()
        {
            List<TypeOwner> types = OwnerHelper.GetTypesOfOwners();
            ViewBag.Types = types;
            return View();
        }

        [HttpPost]
        public ActionResult RegisterUser(RegisterUser user_reg, List<string> phones, string type_owner,
            string newvalue)
        {
            if (!OwnerHelper.IsValidEmail(user_reg.Email))
            {
                ModelState.AddModelError("Email", "Користувач з такою електронною адресою вже зареєстрований!");
            }

            if (!OwnerHelper.IsValidLogin(user_reg.Login))
            {
                ModelState.AddModelError("Login", "Користувач з таким логіном вже зареєстрований!");
            }

            CommonMapper ModelMapper = new CommonMapper();
            Owner user = (Owner)ModelMapper.Map(user_reg, typeof(RegisterUser), typeof(Owner));

            if (type_owner == "new" && newvalue == "")
            {
                ModelState.AddModelError("TypeOwner", "Введіть посаду співвласника!");
            }

            bool flag = false;
            foreach(string s in phones)
            {
                if (s == "")
                    flag = true;
            }

            if(flag)
            {
                ModelState.AddModelError("TypeOwner", "Введіть всі телефони співвласника!");
            }

            if (ModelState.IsValid)
            {
                int id_type;
                if(type_owner == "new")
                {
                    id_type = OwnerHelper.AddNewType(newvalue);
                }
                else
                {
                    id_type = Convert.ToInt32(type_owner);
                }

                Owner current_owner = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
                UserHelper.AddOwner(user, phones, current_owner.OOABID, id_type);
                return View("RegistrationSuccessful");
            }
            else
            {
                List<TypeOwner> types = OwnerHelper.GetTypesOfOwners();
                ViewBag.Types = types;
                return View("Registration");
            }
        }

        public ActionResult LogIn(string login, string password)
        {
            int? id = UserHelper.IsValidLoginAndPassword(login, password);
            
            if(id != null)
            {
                Session["user_id"] = id.ToString();
                return RedirectToAction("News", "Novelty"); 
            }
            else
                TempData["ResultLogIn"] = "Не існує користувача з таким логіном та паролем";
            return RedirectToAction("Index", "Home");           
        }
        public ActionResult LogOut()
        {
            Session["user_id"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult UserInfo()
        {
            Owner user = OwnerHelper.GetOwnerById(Convert.ToInt32(Session["user_id"].ToString()));
            return PartialView(user);           
        }

        public ActionResult ForgetPassword()
        {
            TempData["Form"] = "Forget";
            return RedirectToAction("Index", "Home");
        }
        public ActionResult SendNewPassword(string mail)
        {
            Owner owner = OwnerHelper.GetOwnerByEmail(mail);
            if (owner == null)
            {
                TempData["Form"] = "Forget";
                TempData["ResultEnterEmail"] = "Не існує користувача з такою адресою";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                UserHelper.ChangePassword(owner);
                TempData["Successful"] = "Новий пароль відправлено на електронну пошту " + owner.Email;
                return RedirectToAction("Index", "Home");
            }
        }

    }
}

Universal-OSBB/Universal-OSBB/Views/Home/Authorization.cshtml
<div class="auth">
 
    <span>@TempData["Successful"]</span>
    @if (TempData["ResultLogIn"] != null)
    {
        <p>
            <span class="field-validation-error">@TempData["ResultLogIn"]</span>
        </p>
    }
    else
    {
        <p>
            Вхід в систему
        </p>
    }
    <form method="post" action="/User/LogIn">
        <input name="login" type="text" value="" size="15" placeholder="Логін" />
        <p>
            <input name="password" type="password" value="" size="15" placeholder="Пароль" />
        <p>
            <input class="mybutton" type="submit" value="Увійти" />
            <br>
            <br>
            @Html.ActionLink("Забули пароль?", "ForgetPassword", "User", null, new { target = "blank" })
        </p>
    </form>
    
</div>

Universal-OSBB/Universal-OSBB/Views/Home/FooterHead.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Owner>
@if(Model.Count()>0)
{
    <div>
        Відповідальні по секторах об'єднання <b>"@Model.First().OOAB.Name"</b>:
        <br>
        @foreach(var item in Model)
        { 
            <span>@item.TypeOwner.Name </span>
            <b>@Html.ActionLink(item.Surname+" "+item.Name + " "+item.MiddleName, "DetailsOwner", "Owner", new { id = item.OwnerID }, null)</b>
            <br>
        }
    </div>
}

Universal-OSBB/Universal-OSBB/Views/Home/FooterOwner.cshtml
@model Universal_OSBB.Models.Entities.Owner

@if(Model != null)
{ 
    <div>
        Головою об'єднання <b>"@Model.OOAB.Name"</b>
        є <b>@Html.ActionLink(Model.Surname + " " + Model.Name + " " + Model.MiddleName, "DetailsOwner", "Owner", new { id = Model.OwnerID }, null)</b>
        <br>електронна пошта: <b>@Model.Email</b><br>
        @if (ViewBag.Phones.Count > 0)
        { 
            <text>контактні телефони:</text>
            int n = ViewBag.Phones.Count;
            for(int i = 0; i<n; i++)
            {
                if(i < n-1)
                {
                    <b>@ViewBag.Phones[i].PhoneNumber, </b>
                }
                else
                {
                    <b>@ViewBag.Phones[i].PhoneNumber</b>
                }
            }
        }
      
    </div>
}

Universal-OSBB/Universal-OSBB/Views/Home/ForgetPassword.cshtml
<div class="auth">
@if (TempData["Successful"] != null)
{
    <span>TempData["Successful"]</span>
}
else
{

    if (TempData["ResultEnterEmail"] != null)
    {
        <p>
            <span class="field-validation-error">@TempData["ResultEnterEmail"]</span>
        </p>
    }
    <form method="post" action="/User/SendNewPassword">
        <p>
            Введіть електронну пошту:
        </p>
        <input name="mail" type="email" value="" placeholder="E-mail" />
        <p>
            <input class="mybutton" type="submit" value="Відправити пароль" />
    </form>
}
</div>

Universal-OSBB/Universal-OSBB/Views/Home/Index.cshtml
@{
    Session["menu_item"] = null;
}
Вітаємо Вас на сайті, де члени ОСББ приймають рішення і знаходять відповіді на питання не виходячи з власного приміщення

Universal-OSBB/Universal-OSBB/Views/Home/LastNews.cshtml
@model IEnumerable<Universal_OSBB.Models.Entities.Message>

<div class="news">
    <span class="news">
        Останні новини об'єднання
    </span>
    <br>
    <ul>
        @foreach (var item in Model)
        {
            <li>@Html.ActionLink(item.Topic, "DetailsNovelty", "Novelty", new { id = item.MessageID }, null)</li>
        }
    </ul>
</div>

Universal-OSBB/Universal-OSBB/Views/Home/MenuHead.cshtml
<div class="mainmenu">
    <ul>
        <li>
            @Html.ActionLink("Новини", "News", "Novelty")    
        </li>
        <li>
            @Html.ActionLink("Опитування", "Interviews", "Interview")
        </li>
        <li>
            @Html.ActionLink("Співвласники", "OwnersHead", "Owner")
        </li>
        <li>
            @Html.ActionLink("Майно", "Rooms", "Property")
        </li>
        <li>
            @Html.ActionLink("Сплата", "PaymentForRooms", "Finance")
        </li>
        <li>
            @Html.ActionLink("Витрати", "CurrentCosts", "Finance")
        </li>
        <li>
            @Html.ActionLink("Профіль", "News", "Novelty")
        </li>
        <li>
            @Html.ActionLink("Вихід", "LogOut", "User")
        </li>
    </ul>
</div>

Universal-OSBB/Universal-OSBB/Views/Home/MenuOwner.cshtml
<div class="mainmenu">
    <ul>
        <li>
            @Html.ActionLink("Новини", "News", "Novelty")    
        </li>
        <li>
            @Html.ActionLink("Опитування", "Interviews", "Interview")
        </li>
        <li>
            @Html.ActionLink("Співвласники", "Owners", "Owner")
        </li>
        <li>
            @Html.ActionLink("Майно", "Rooms", "Property")
        </li>
        <li>
            @Html.ActionLink("Сплата", "PaymentForRooms", "Finance")
        </li>
        <li>
            @Html.ActionLink("Витрати", "CurrentCosts", "Finance")
        </li>
        <li>
            @Html.ActionLink("Профіль", "News", "Novelty")
        </li>
        <li>
            @Html.ActionLink("Вихід", "LogOut", "User")
        </li>
    </ul>
</div>

Universal-OSBB/Universal-OSBB/Views/Home/SubMenuHead.cshtml
<div class="sub_menu">
<ul>
@if (Session["menu_item"] != null)
{
    switch (Session["menu_item"].ToString())
    {
        case "news":
            {
                    <li>
                        @Html.ActionLink("Розмістити повідомлення", "CreateNovelty", "Novelty")
                    </li>

                    break;
                }
            case "interviews":
                {
                    <li>
                        @Html.ActionLink("Розмістити опитування", "CreateInterview", "Interview")
                    </li>
                    break;
                }
            case "owners":
                {
                    <li>
                        @Html.ActionLink("Зареєструвати співвласника", "Registration", "User")
                    </li>
                    break;
                }
            case "properties":
                {
                    <li>
                        @Html.ActionLink("Приміщеня", "Rooms", "Property")
                    </li>
                    <li>
                        @Html.ActionLink("Зареєструвати приміщення", "CreateRoom", "Property")
                    </li>
                    <li>
                        @Html.ActionLink("Будинки", "Houses", "Property")
                    </li>
                    <li>
                        @Html.ActionLink("Зареєструвати будинок", "CreateHouse", "Property")
                    </li>
                    break;
                }

            case "payments":
                {
                    <li>
                        @Html.ActionLink("Сплата за мої приміщення", "PaymentForRooms", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Сплата коштів співвласником", "CreateReceipt", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Абонплата", "MonthlyFee", "Finance")
                    </li>
                    
                    <li>
                        @Html.ActionLink("Боржники", "Deptors", "Finance")
                    </li>

                    break;
                }

            case "costs":
                {
                    <li>
                        @Html.ActionLink("Поточні витрати", "CurrentCosts", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Планування витрат", "CostPlanning", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Витрачені кошти", "SpentMoneySearch", "Finance")
                    </li>
                    break;
                }
    }
}
</ul>
</div>

Universal-OSBB/Universal-OSBB/Views/Home/SubMenuOwner.cshtml
<div class="sub_menu">
<ul>
    @if (Session["menu_item"] != null)
    {
        switch (Session["menu_item"].ToString())
        {
            case "news":
                {
                        <li>
                            @Html.ActionLink("Розмістити повідомлення", "CreateNovelty", "Novelty")
                        </li>
                        <li>
                            @Html.ActionLink("Заява на ім'я голови", "StatementToHead", "Owner")
                        </li>

                    break;
                }
            case "interviews":
                {
                    <li>
                        @Html.ActionLink("Розмістити опитування", "CreateInterview", "Interview")
                    </li>
                    break;
                }
            case "properties":
                {
                    <li>
                        @Html.ActionLink("Приміщеня", "Rooms", "Property")
                    </li>
                    <li>
                        @Html.ActionLink("Будинки", "Houses", "Property")
                    </li>
                    break;
                }

            case "payments":
                {
                    <li>
                        @Html.ActionLink("Сплата за мої приміщення", "PaymentForRooms", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Абонплата", "MonthlyFee", "Finance")
                    </li>

                    <li>
                        @Html.ActionLink("Боржники", "Deptors", "Finance")
                    </li>

                    break;
                }

            case "costs":
                {
                    <li>
                        @Html.ActionLink("Поточні витрати", "CurrentCosts", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Планування витрат", "CostPlanningOwners", "Finance")
                    </li>
                    <li>
                        @Html.ActionLink("Витрачені кошти", "SpentMoneySearch", "Finance")
                    </li>
                    break;
                }
        }
    }
</ul>
</div>